### ISSUE TITLE
Undefined symbol error

### ISSUE THREAD

**Issue by Scott-Hickmann** [riderodd/react-native-vosk#21]
Hi, I'm having issues rebuilding my Xcode project after installing pods. I'm using React Native 0.70.1 and React Native Vosk 0.1.9, and I am building on an M1 Mac. Xcode is not providing any more details to the errors shown in the image below. Do you know what they could mean / where to investigate?

Thanks

<img width="223" alt="Screen Shot 2022-09-18 at 6 29 06 PM" src="https://user-images.githubusercontent.com/24500706/190937230-420e89b9-7045-4b3b-8567-311105fde99c.png">

**Comment by riderodd** [comment]
Hi @Scott-Hickmann,

Have you requested the libvosk build for iOS as mentioned in [the iOS section](https://github.com/riderodd/react-native-vosk#ios) ?
Can you check your libvosk.xcframework is in the right directory ?

**Comment by laurent22** [comment]
Would it be possible to bundle this file by default? Otherwise it requires patching the module, which is not ideal

**Comment by riderodd** [comment]
@laurent22 : Alphaceiphei just allowed me to release the lib with in the repo. I couldn't release it before because of license agreement. Update to latest version and it should work.
