### ISSUE TITLE
example not works

### ISSUE THREAD

**Issue by sirramin** [riderodd/react-native-vosk#36]
When I press Record after a moment nothing happens and transcription does not work.

**Comment by riderodd** [comment]
Without more context it's gonna be hard to help. What's your environment? How did you run the example ?

**Comment by sirramin** [comment]
I run it on my android phone with Android 11

**Comment by sirramin** [comment]
And your documentation is wrong it's refrencing to react-native-voice-recognition

**Comment by riderodd** [comment]
Yep it's the old name of the package, we need to update this (feel free to open a PR, it's an open source project ;) )
I quote https://reactnative.dev/docs/environment-setup?os=windows&platform=android

> Building a React Native app with native code, however, requires the Android 13 (Tiramisu) SDK in particular.

Can you try in the android studio emulator to see if the problem still occurs? It's running fine on my side.

**Comment by riderodd** [comment]
I've updated the README to work with the current package name, so closing now
