### ISSUE TITLE
Transcribe audio files [Feature]

### ISSUE THREAD

**Issue by abdoemr11** [riderodd/react-native-vosk#52]
I can't find a way to use this library to transcribe audio files only real time transcribing.  As far as I can tell, the audio file transcribing is possible in vosk but it isn't implemented. So, could you implement it?

**Comment by riderodd** [comment]
For sure that would be a great improvement. For now I'm too busy, but we will keep it in mind. If you can contribute feel free to do a PR with the implementaiton !

**Comment by abdoemr11** [comment]
Ok, I'm getting things up and running. but where exactly should I put the model folder. I tried to put it on example/android/app/assets but it gives me this error 
`java.io.FileNotFoundException: vosk-model-small-ar/uuid`

**Comment by riderodd** [comment]
Check the readme, you're in the wrong folder. Models should live in your
android/ main folder.
