### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by fkurushin** [riderodd/react-native-vosk#63]
Does this library download model any time user interacts with the app or with the web-app?

**Comment by riderodd** [comment]
The NPM package is not up-to-date for now, so it does not download any model, you have to download it yourself.
If you use the git repo as source, you can use dynamic model loading, but the package itself doesn't download anything, you have to do it by yourself. Look at the readme, there are examples.
Moreover, there's no compatibility with web environment, it's only iOS/Android native.

**Comment by fkurushin** [comment]
@riderodd  Okay, does it load the same model every time the user opens the app, or does it load it once at a time?

**Comment by riderodd** [comment]
What do you mean by "load" ? As I said, the package does not download anything. You have to download a model and put it in your app. Then you load it from your local filesystem into memory using the package.
