### ISSUE TITLE
Crashes on iOS

### ISSUE THREAD

**Issue by maxfadeev** [riderodd/react-native-vosk#69]
I followed the steps, but it keeps crashing on iOS both on simulator and device. Not sure if I missed something.
Also, it's not clear whether I should load the model via `loadModel` if put the model into the bundle or not, because it's saying `Primarily intended for models that are not included in the app’s Main Bundle`. Apparently I should anyway.
Here is the exception.
<img width="756" alt="Screenshot 2024-11-02 at 16 46 31" src="https://github.com/user-attachments/assets/9cc3ddf1-811b-4162-861e-3b46a87542cf">

**Comment by joaolobao380** [comment]
I have the same problem

**Comment by joaolobao380** [comment]
@maxfadeev Did you manage to find any solution?

**Comment by maxfadeev** [comment]
No it just doesn't work, I tried everything I could. I switched to `react-native-voice`.

**Comment by joaolobao380** [comment]
I got it. I'll try a little more, any news I'll send here

**Comment by joaolobao380** [comment]
@maxfadeev I think I solved it, follow below:

![Captura de Tela 2024-11-07 às 21 32 24](https://github.com/user-attachments/assets/49ba3497-91be-4a79-86ae-042e2240cd92)

You will add the model manually to the copy bundle resources. It should work
