### ISSUE TITLE
 ERROR  [java.io.FileNotFoundException: model-fr-fr/uuid]

### ISSUE THREAD

**Issue by linhuanfeng** [riderodd/react-native-vosk#83]
**Describe the bug**
I successfully ran the example in this repository, but when I clicked load mdel on the Android app, an error occurred

**To Reproduce**
1. yarn install
2. yarn android
2. Click load medel button

**Expected behavior**

**Screenshots**
![fb8b84eab02aa151672d36fc0cd8ad8](https://github.com/user-attachments/assets/7791e676-5142-44e2-a0a8-a058a3f2c471)
![65dc6a978d667fdc1103144bb9fb4ff](https://github.com/user-attachments/assets/d7331e82-c025-4b08-918a-24ea84a03155)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: oppo reno5 k 5g
 - OS: android 12

**Additional context**

**Comment by chenvvy** [comment]
怎么解决的哥们？
